name = "Monorepo"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Monorepo"]

[leanOptions]
maxHeartbeats = 10000000
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Monorepo"
