name = "OneGroup"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["OneGroup"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "OneGroup"
